spring:
  config:
    activate:
      on-profile: dev
  output:
    ansi:
      enabled: always

logging:
  level:
    org.springframework.core.env.PropertySourcesPropertyResolver: DEBUG
    org:
      springframework:
        core:
          env:
            PropertySourcesPropertyResolver: DEBUG